---
apiVersion: v1
kind: Service
metadata:
  name: react-speed-reader-service
spec:
  type: LoadBalancer
  selector:
    app: react-speed-reader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80